#!/bin/bash
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"

export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin
export PATH=$JAVA_HOME/bin:$M2:$PATH
cd $OPENSHIFT_DATA_DIR
cd team-up-service
mvn clean install -s $OPENSHIFT_DATA_DIR/settings.xml
cd target
java -jar  team-up-service-1.0-SNAPSHOT.jar --server.port=8080 --server.address=127.11.244.1