-- MySQL Script generated by MySQL Workbench
-- 10/24/15 17:47:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teamup` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `teamup` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamup`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `sex` VARCHAR(1) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamup`.`group` (
  `id_group` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nfc_code` VARCHAR(255) NOT NULL,
  `radius` DOUBLE NOT NULL,
  `id_creator` INT NOT NULL,
  PRIMARY KEY (`id_group`, `id_creator`),
  INDEX `fk_group_user_idx` (`id_creator` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  UNIQUE INDEX `nfc_code_UNIQUE` (`nfc_code` ASC),
  CONSTRAINT `fk_group_user`
    FOREIGN KEY (`id_creator`)
    REFERENCES `teamup`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupmembers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamup`.`groupmembers` (
  `user_id_user` INT NOT NULL,
  `group_id_group` INT NOT NULL,
  `lat` FLOAT(10,6) NOT NULL,
  `lng` FLOAT(10,6) NOT NULL,
  PRIMARY KEY (`user_id_user`, `group_id_group`),
  INDEX `fk_groupmembers_group1_idx` (`group_id_group` ASC),
  CONSTRAINT `fk_groupmembers_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `teamup`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupmembers_group1`
    FOREIGN KEY (`group_id_group`)
    REFERENCES `teamup`.`group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
